version: '3.1'
services:
     jenkins:
        build: master
        ports:
            - '8080:8080'
            - '50000:50000'
        environment:
            - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

     agent:
        build: 
          context: . 
          dockerfile: slave/Dockerfile
        hostname: agent 
        depends_on:
           - jenkins

      agent_swarm: 
         build:
           context: .
           dockerfile: slave/dockerfile_slaveswarm

     sonarqube:
        build: sonarqube
        ports:
           - '9000:9000'
        restart: always
        depends_on:
            - jenkins 
  
     artifactory:
        image: docker.bintray.io/jfrog/artifactory-oss:latest
        ports:
           - '8081:8081'
        volumes:
        - /opt/artifactory:/var/opt/jfrog/artifactory
        depends_on:
            - jenkins
#    Add extra Java options by uncommenting the following lines
    environment:
     - EXTRA_JAVA_OPTIONS=-Xmx2g
        restart: always
        ulimits:
          nproc: 65535
          nofile:
              soft: 32000
              hard: 40000
